[package]
name = "voxel_renderer"
version = "0.1.0"
edition = "2021"

[features]
default = ["glam/bytemuck"]

[dependencies]
thiserror = "1.0"
anyhow = "1.0"
vulkano = "0.34"
shaderc = "0.8"
image = "0.25"
glam = "0.29"
